name: EAS Build and Submit

on:
  push:
    branches:
      - main  # Cambia esto al nombre de la rama en la que deseas activar el flujo

jobs:
  build_and_submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Cambia esto a la versión de Node.js que necesitas

      -name: Install Dependencies
         run: npm ci

      - name: Install expo-cli
        run: npm install -g expo-cli

      - name: Install eas-cli
        run: npm install -g eas-cli

      - name: Authenticate with EAS
        run: |
          echo ${{ secrets.EAS_EMAIL }} > eas-email.txt
          echo ${{ secrets.EAS_PASSWORD }} > eas-password.txt
          eas login --email "$(cat eas-email.txt)" --password "$(cat eas-password.txt)"

      - name: Build Android
        run: eas build --platform android

      - name: Submit to Play Console
        run: eas submit -p android --latest