name: Expo Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Install dependencies
        run: npm install
        
      - name: Install Expo CLI
        run: npm install -g expo-cli
        
      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_ACCESS_TOKEN }}    

      - name: Authenticate with EAS
        run: npx eas whoami --token ${{ secrets.EAS_BUILD_TOKEN }}
        
      - name: Build Android
        run: npx eas build --platform android
        
      - name: Submit to EAS
        run: npx eas submit -p android --latest
        env:
          EXPO_CLI_NO_DOCTOR: 'true'
        
      - name: Publish Expo
        run: expo publish
        env:
          EXPO_CLI_NO_DOCTOR: 'true'
        
      - name: Cleanup
        run: npm ci