name: EAS Build and Submit

on:
  push:
    branches:
      - main

jobs:
  build_and_submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm ci

      - name: Install expect
        run: sudo apt-get install expect -y

      - name: Install expo-cli
        run: npm install -g expo-cli

      - name: Install eas-cli
        run: npm install -g eas-cli

      - name: Authenticate with EAS
        run: |
          echo -e "${{ secrets.EAS_EMAIL }}\n${{ secrets.EAS_PASSWORD }}" | expect -c '
            spawn eas login
            expect "Email:"
            send "$env(EXPECT_EOL)"
            expect "Password:"
            send "$env(EXPECT_EOL)"
            interact
          '
        env:
          EXPECT_EOL: "\r"

      - name: Build Android
        run: eas build --platform android

      - name: Submit to Play Console
        run: eas submit -p android --latest